version: "3.3"

services:
  frontend:
    container_name: preservetube-frontend
    image: preservetube/frontend
    networks:
      - public
    restart: on-failure
    volumes:
      - ./.env:/usr/src/preservetube/frontend/.env

networks:
  public:
    external:
      name: public